package:
  name: libxcrypt-el10-x86_64
  version: 4.4.36

source:
  - url: https://download.rockylinux.org/vault/rocky/10.0/BaseOS/x86_64/os/Packages/l/libxcrypt-4.4.36-10.el10.x86_64.rpm
    sha256: 06bb13ba608b57582b3dfc453645ec547d99b5fba934b4732c6c05b630b3f88b
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and x86_64)]
  number: {{ build_number }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-64 2.39.*
  host:
  run:
    - sysroot_linux-64 2.39.*

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el10-linux-gnu/sysroot/usr/lib64/fipscheck/libcrypt.so.2.0.0.hmac
    - test -f ${PREFIX}/x86_64-conda_el10-linux-gnu/sysroot/usr/lib64/fipscheck/libcrypt.so.2.0.0.hmac

# LICENSING says LGPL-2.1-or-later, COPYING.LIB is that license
about:
  home: https://github.com/besser82/libxcrypt
  license: LGPL-2.1-or-later  # LGPL-2.1-or-later AND BSD-3-Clause AND BSD-2-Clause AND BSD-2-Clause-FreeBSD AND 0BSD AND CC0-1.0 AND LicenseRef-Fedora-Public-Domain
  license_family: LGPL
  license_file:
    - AUTHORS
    - COPYING.LIB
    - LICENSING
  summary: (CDT) Extended crypt library for descrypt, md5crypt, bcrypt, and others
  description: |
    libxcrypt is a modern library for one-way hashing of passwords.  It
    supports a wide variety of both modern and historical hashing methods:
    yescrypt, gost-yescrypt, scrypt, bcrypt, sha512crypt, sha256crypt,
    md5crypt, SunMD5, sha1crypt, NT, bsdicrypt, bigcrypt, and descrypt.
    It provides the traditional Unix crypt and crypt_r interfaces, as well
    as a set of extended interfaces pioneered by Openwall Linux, crypt_rn,
    crypt_ra, crypt_gensalt, crypt_gensalt_rn, and crypt_gensalt_ra.

    libxcrypt is intended to be used by login(1), passwd(1), and other
    similar programs; that is, to hash a small number of passwords during
    an interactive authentication dialogue with a human. It is not suitable
    for use in bulk password-cracking applications, or in any other situation
    where speed is more important than careful handling of sensitive data.
    However, it is intended to be fast and lightweight enough for use in
    servers that must field thousands of login attempts per minute.

    This version of the library does not provide the legacy API functions
    that have been provided by glibc's libcrypt.so.1.
  doc_url: https://github.com/besser82/libxcrypt
  dev_url: https://github.com/besser82/libxcrypt

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
