package:
  name: java-21-openjdk-el10-x86_64
  version: 21.0.9.0.10

source:
  - url: https://download.rockylinux.org/vault/rocky/10.0/AppStream/x86_64/os/Packages/j/java-21-openjdk-21.0.9.0.10-1.el10.x86_64.rpm
    sha256: 179553a695016555acce49c54d4810b06f363b4f605f9fb87a0a2beec6e696ef
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and x86_64)]
  number: {{ build_number }}
  noarch: generic
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-64 2.39.*
  host:
    - ca-certificates
    - xorg-libx11
    - xorg-libxext
    - xorg-libxi
    - xorg-libxrender
    - xorg-libxtst
  run:
    - sysroot_linux-64 2.39.*
    - java-21-openjdk-headless-el10-x86_64 ==21.0.9.0.10 *_{{ build_number }}
    - ca-certificates
    - fontconfig
    - xorg-libx11
    - xorg-libxcomposite
    - xorg-libxext
    - xorg-libxi
    - xorg-libxrender
    - xorg-libxtst

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el10-linux-gnu/sysroot/usr/lib/jvm/java-21-openjdk/lib/libjawt.so

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib  # ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv2.0 and Public Domain and W3C and zlib and ISC and FTL and RSA
  license_family: Other
  summary: (CDT) OpenJDK 21 Runtime Environment
  description: |
    The OpenJDK 21 runtime environment.
  doc_url: http://openjdk.java.net/
  dev_url: http://openjdk.java.net/

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
