package:
  name: libtirpc-el10-x86_64
  version: 1.3.5

source:
  - url: https://download.rockylinux.org/vault/rocky/10.0/BaseOS/x86_64/os/Packages/l/libtirpc-1.3.5-1.el10.x86_64.rpm
    sha256: f14f685673bfc0372a4487873862725b6ca5d08f84c7ced05c678825129a68dc
    no_hoist: true
    folder: binary

build:
  skip: True  # [not (linux and x86_64)]
  number: {{ build_number }}
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - sysroot_linux-64 2.39.*
  host:
  run:
    - sysroot_linux-64 2.39.*
    - krb5

test:
  commands:
    - test -f ${PREFIX}/x86_64-conda_el10-linux-gnu/sysroot/lib64/libtirpc.so.3
    - test -f ${PREFIX}/x86_64-conda_el10-linux-gnu/sysroot/lib64/libtirpc.so.3.0.0

about:
  home: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary
  license: BSD-3-Clause  # SISSL AND BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
  summary: (CDT) Transport Independent RPC Library
  description: |
    This package contains SunLib's implementation of transport-independent
    RPC (TI-RPC) documentation.  This library forms a piece of the base of
    Open Network Computing (ONC), and is derived directly from the
    Solaris 2.3 source.

    TI-RPC is an enhanced version of TS-RPC that requires the UNIX System V
    Transport Layer Interface (TLI) or an equivalent X/Open Transport Interface
    (XTI).  TI-RPC is on-the-wire compatible with the TS-RPC, which is supported
    by almost 70 vendors on all major operating systems.  TS-RPC source code
    (RPCSRC 4.0) remains available from several internet sites.
  doc_url: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary
  dev_url: http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary

extra:
  recipe-maintainers:
    - conda-forge/help-cdts
